(ns skill-match.data)

; todo move this to a separate static edn file, may have too look up with client-side http

(def ^:const skills-data
  {"Technologies"
   ["Java"
    "C#/.NET"
    "SQL"
    "Microsoft SQL Server (TSQL)"
    "MongoDB"
    "GitHub"
    "JavaScript/TypeScript"
    "Azure DevOps"
    "Linux"
    "PostgreSQL"
    "PostGIS" 
    "Git"
    "JUnit Testing Framework"
    "Kubernetes & Docker"
    "JSON"
    "XML"
    "gRPC/ProtoBuf"
    "Kafka"
    "JetBrains IntelliJ"
    "JetBrains Rider"
    "React" 
    "React.js"
    ".NET MVC"
    ".NET Core"
    "LINQ"
    "C/C++"
    "Visual Studio"
    "Python"
    "Clojure"
    "ClojureScript"]


   "Concepts & Practices"
   ["Observability"
    "Legacy System Modernization"
    "Functional Programming"
    "Test-Driven Design (TDD)"
    "Microservices Architecture"
    "Code Reviews"
    "Code Review"
    "SOLID Software Principles"
    "Distributed Systems Design"
    "Object-Oriented Programming (OOP)"
    "RESTful APIs"
    "Agile/Scrum"
    "Software Development Lifecycle (SDLC)"
    "Database Design"
    "Full Stack Architecture"]})

